# Generated by Django 4.2.3 on 2023-07-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonapp', '0002_comment_image_comment_user_post_image_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
