# Generated by Django 4.2.3 on 2023-07-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonapp', '0004_remove_post_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='빈 댓글입니다.'),
        ),
    ]
