# Generated by Django 4.2.3 on 2023-08-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonapp', '0005_alter_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
